import Navbar from "@/components/Navbar";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import {
    ChatBubbleLeftEllipsisIcon,
    ComputerDesktopIcon,
    HomeIcon,
} from "@heroicons/react/24/outline";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const navigation = [
    {
        name: "Dashboard",
        icon: HomeIcon,
        href: "/",
        current: true,
    },
    {
        name: "Logs",
        icon: ComputerDesktopIcon,
        href: "/logs",
        current: false,
    },
    {
        name: "Chat",
        icon: ChatBubbleLeftEllipsisIcon,
        href: "/chat",
        current: false,
    },
];

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <main className="flex p-5 gap-5 items-end justify-center w-screen h-screen overflow-hidden bg-neutral-950">
                    <Navbar navigation={navigation} />
                    {children}
                </main>
            </body>
        </html>
    );
}
